
BLENDER="C:\Program Files\Blender Foundation\Blender 4.5\blender.exe"
DIST=../dist

all : \
    $(DIST)/road.pnct \
    $(DIST)/road.scene \

$(DIST)/road.scene : road.blend export-scene.py
    $(BLENDER) --background --python export-scene.py -- "road.blend:Main" "$(DIST)/road.scene"

$(DIST)/road.pnct : road.blend export-meshes.py
    $(BLENDER) --background --python export-meshes.py -- "road.blend:Main" "$(DIST)/road.pnct" 
